version: '3.9'

services:
  ocr:
    build:
      context: ./OCR
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - app-network

  rag:
    build:
      context: ./RAG
      dockerfile: ./RAG/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - ocr
      - chroma
    environment:
      - OCR_URL=http://ocr:8081 # Pass OCR service URL as an environment variable
      - CHROMA_API_URL=http://chroma:8000 # Pass ChromaDB service URL as an environment variable
    networks:
      - app-network

  chroma:
    image: ghcr.io/chroma-core/chroma:0.6.2
    container_name: chroma
    ports:
      - "8000:8000"
    volumes:
      - index_data:/chroma/.chroma/index
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  index_data:
    driver: local
  backups:
    driver: local