// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistance.Database;

#nullable disable

namespace Persistance.Migrations
{
    [DbContext(typeof(DocMinerDbContext))]
    [Migration("20250201190832_DocumentCollectionsAndProcessedDocuments")]
    partial class DocumentCollectionsAndProcessedDocuments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("Persistance.Models.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DocumentCollectionId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StorageLocation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DocumentCollectionId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("Persistance.Models.DocumentCollection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DocumentCollections");
                });

            modelBuilder.Entity("Persistance.Models.ProcessedDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DocumentCollectionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DocumentCollectionId");

                    b.ToTable("ProcessedDocuments");
                });

            modelBuilder.Entity("Persistance.Models.Document", b =>
                {
                    b.HasOne("Persistance.Models.DocumentCollection", null)
                        .WithMany("Documents")
                        .HasForeignKey("DocumentCollectionId");
                });

            modelBuilder.Entity("Persistance.Models.ProcessedDocument", b =>
                {
                    b.HasOne("Persistance.Models.DocumentCollection", null)
                        .WithMany("ProcessedDocuments")
                        .HasForeignKey("DocumentCollectionId");
                });

            modelBuilder.Entity("Persistance.Models.DocumentCollection", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("ProcessedDocuments");
                });
#pragma warning restore 612, 618
        }
    }
}
